# Generated by Django 3.2.8 on 2021-10-30 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_produto', models.CharField(max_length=150, verbose_name='Nome do Produto')),
                ('dc_produto', models.TextField(verbose_name='Descrição')),
                ('vl_produto', models.FloatField(verbose_name='Valor do Produto')),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Cadastro')),
                ('st_produto', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1, verbose_name='Situação do Produto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_produto_categoria1', to='anuncios.categoria')),
            ],
        ),
    ]
