# Generated by Django 3.2.8 on 2021-10-30 17:16

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anuncios', '0003_produto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nm_icone',
            field=models.CharField(default='fas fa-mobile-alt fa-3x', help_text='Opções no site https://fontawesome.com.', max_length=20, verbose_name='Nome do Ícone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='usuario',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='fk_produto_user1', to=settings.AUTH_USER_MODEL),
        ),
    ]
