# Generated by Django 3.2.8 on 2021-10-30 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anuncios', '0004_auto_20211030_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_condominio', models.CharField(max_length=150, verbose_name='Nome do Condomínio')),
                ('nm_logradouro', models.CharField(max_length=80, verbose_name='Nome do Logradouro')),
                ('nr_logradouro', models.IntegerField(null=True, verbose_name='Número')),
                ('nm_bairro', models.CharField(max_length=45, verbose_name='Bairro')),
                ('tx_complemento', models.CharField(max_length=45, verbose_name='Complemento')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('nm_cidade', models.CharField(max_length=60, verbose_name='Cidade')),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_contato', models.CharField(max_length=45, verbose_name='Tipo de Contato')),
                ('tx_contato', models.CharField(choices=[('Telefone', 'Telefone'), ('WhatsApp', 'WhatsApp'), ('Telegram', 'Telegram'), ('E-Mail', 'E-Mail')], max_length=80, verbose_name='Contato')),
                ('condominios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_contato_condominio1', to='anuncios.contato')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_contato_user1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
