# Generated by Django 3.2.8 on 2021-10-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0006_auto_20211030_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='tp_contato',
            field=models.CharField(choices=[('Telefone', 'Telefone'), ('WhatsApp', 'WhatsApp'), ('Telegram', 'Telegram'), ('E-Mail', 'E-Mail')], max_length=45, verbose_name='Tipo de Contato'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='tx_contato',
            field=models.CharField(max_length=80, verbose_name='Contato'),
        ),
    ]
