# Generated by Django 3.2.8 on 2021-10-31 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anuncios', '0007_auto_20211030_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_contato_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vl_nota', models.IntegerField(max_length=1, verbose_name='Nota')),
                ('tx_comentario', models.CharField(max_length=150, null=True, verbose_name='Comentário')),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Cadastro')),
                ('anunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_avaliacao_user2', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_avaliacao_user1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
