# Generated by Django 3.2.8 on 2021-10-31 14:14

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anuncios', '0007_auto_20211030_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_contato_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_titulo_servico', models.CharField(max_length=80, verbose_name='Titulo do Serviço')),
                ('dc_servico', models.TextField(verbose_name='Descrição do Serviço')),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Cadastro')),
                ('st_servico', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1, verbose_name='Situação do Serviço')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_servico_categoria1', to='anuncios.categoria')),
                ('usuario', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='fk_produto_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
