# Generated by Django 3.2.8 on 2021-10-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0008_auto_20211031_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nm_icone',
            field=models.CharField(help_text='Opções no site https://fontawesome.com.', max_length=30, verbose_name='Nome do Ícone'),
        ),
    ]
