# Generated by Django 3.2.8 on 2021-10-31 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0008_auto_20211031_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='vl_nota',
            field=models.IntegerField(verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='condominios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_contato_condominio1', to='anuncios.condominio'),
        ),
    ]
