# Generated by Django 3.2.8 on 2021-10-31 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0008_auto_20211031_1114'),
        ('anuncios', '0009_auto_20211031_1225'),
    ]

    operations = [
    ]
