# Generated by Django 3.2.8 on 2021-10-31 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0009_alter_categoria_nm_icone'),
        ('anuncios', '0010_merge_0008_auto_20211031_1114_0009_auto_20211031_1225'),
    ]

    operations = [
    ]
