# Generated by Django 3.2.8 on 2021-11-01 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0011_auto_20211031_1608'),
        ('anuncios', '0011_merge_20211031_1725'),
    ]

    operations = [
    ]
